{% set name = "invest-ucm-calibration" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/invest-ucm-calibration-{{ version }}.tar.gz
  sha256: 3fe5a0ee19495ce1642e022acc969a83f6558cb984b14af72ba588c15bdb352e

build:
  entry_points:
    - invest-ucm-calibration=invest_ucm_calibration.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fire
    - fiona >=1.0.0
    - natcap.invest >=3.11.0
    - rasterio >=1.0.0
    - rioxarray
    - scikit-learn >=1.0.0
    - simanneal >=0.5.0
    - xarray

test:
  imports:
    - invest_ucm_calibration
  commands:
    - pip check
    - invest-ucm-calibration --help
  requires:
    - pip

about:
  home: https://github.com/martibosch/invest-ucm-calibration
  summary: Automated calibration of the InVEST urban cooling model with simulated annealing
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
